trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Building Academic Performance Evaluator"
  displayName: Build

- script: echo "Running Tests"
  displayName: Test

- script: echo "Deploying Application"
  displayName: Deploy